site_name: kanjirest
site_description: Kanj Django REST for android app
repo_url: https://github.com/maaslak/kanji-rest
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/maaslak">maaslak</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
